version: '3.4'

services:
  catalogdb:
    image: mongo

  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
  basketdb:
    image: redis:alpine
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  mongo_data:
