version: '3.4'

services:
  identitydb:
    restart: always
    container_name: identitydb
    environment:
      SA_PASSWORD: SwN741589631
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db